// default package
// Generated May 20, 2015 1:19:23 PM by Hibernate Tools 3.6.0
package org.gradle;
/**
 * Follower generated by hbm2java
 */
public class Follower implements java.io.Serializable {

	private Integer id;
	private User user;
	private Story story;

	public Follower() {
	}

	public Follower(User user, Story story) {
		this.user = user;
		this.story = story;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public Story getStory() {
		return this.story;
	}

	public void setStory(Story story) {
		this.story = story;
	}

}
