// default package
// Generated May 20, 2015 1:19:23 PM by Hibernate Tools 3.6.0
package org.gradle;
/**
 * Participant generated by hbm2java
 */
public class Participant implements java.io.Serializable {

	private Integer id;
	private User user;
	private Fragment fragment;

	public Participant() {
	}

	public Participant(User user, Fragment fragment) {
		this.user = user;
		this.fragment = fragment;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public Fragment getFragment() {
		return this.fragment;
	}

	public void setFragment(Fragment fragment) {
		this.fragment = fragment;
	}

}
