// default package
// Generated May 20, 2015 1:19:23 PM by Hibernate Tools 3.6.0
package org.gradle;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Story generated by hbm2java
 */
public class Story implements java.io.Serializable {

	private Integer id;
	private String title;
	private String description;
	private Date lastUpdate;
	private boolean finished;
	private Set followers = new HashSet(0);
	private Set fragments = new HashSet(0);

	public Story() {
	}

	public Story(String title, String description, Date lastUpdate,
			boolean finished) {
		this.title = title;
		this.description = description;
		this.lastUpdate = lastUpdate;
		this.finished = finished;
	}

	public Story(String title, String description, Date lastUpdate,
			boolean finished, Set followers, Set fragments) {
		this.title = title;
		this.description = description;
		this.lastUpdate = lastUpdate;
		this.finished = finished;
		this.followers = followers;
		this.fragments = fragments;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Date getLastUpdate() {
		return this.lastUpdate;
	}

	public void setLastUpdate(Date lastUpdate) {
		this.lastUpdate = lastUpdate;
	}

	public boolean isFinished() {
		return this.finished;
	}

	public void setFinished(boolean finished) {
		this.finished = finished;
	}

	public Set getFollowers() {
		return this.followers;
	}

	public void setFollowers(Set followers) {
		this.followers = followers;
	}

	public Set getFragments() {
		return this.fragments;
	}

	public void setFragments(Set fragments) {
		this.fragments = fragments;
	}

}
