// default package
// Generated May 20, 2015 1:19:23 PM by Hibernate Tools 3.6.0
package org.gradle;

import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {

	private Integer id;
	private String gid;
	private String gname;
	private Set followers = new HashSet(0);
	private Set fragments = new HashSet(0);
	private Set participants = new HashSet(0);

	public User() {
	}

	public User(String gid, String gname) {
		this.gid = gid;
		this.gname = gname;
	}

	public User(String gid, String gname, Set followers, Set fragments,
			Set participants) {
		this.gid = gid;
		this.gname = gname;
		this.followers = followers;
		this.fragments = fragments;
		this.participants = participants;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getGid() {
		return this.gid;
	}

	public void setGid(String gid) {
		this.gid = gid;
	}

	public String getGname() {
		return this.gname;
	}

	public void setGname(String gname) {
		this.gname = gname;
	}

	public Set getFollowers() {
		return this.followers;
	}

	public void setFollowers(Set followers) {
		this.followers = followers;
	}

	public Set getFragments() {
		return this.fragments;
	}

	public void setFragments(Set fragments) {
		this.fragments = fragments;
	}

	public Set getParticipants() {
		return this.participants;
	}

	public void setParticipants(Set participants) {
		this.participants = participants;
	}

}
